# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

# def options(opt):
#     pass

# def configure(conf):
#     conf.check_nonfatal(header_name='stdint.h', define_name='HAVE_STDINT_H')

def build(bld):
    module = bld.create_ns3_module('traffic-control', ['core', 'network'])
    module.source = [
      'model/traffic-control-layer.cc',
      'model/packet-filter.cc',
      'model/queue-disc.cc',
      'model/pfifo-fast-queue-disc.cc',
      'model/red-queue-disc.cc',
      'model/codel-queue-disc.cc',
      'model/fq-codel-queue-disc.cc',
      'model/pie-queue-disc.cc',
      'model/FlowScheduler.cc',
      'model/MyPipeline.cc',
      'model/MyScheduling.cc',
      'model/PIFO.cc',
      'model/SimplePIFO.cc',
      'model/vPIFO.cc',
      'model/vPIFO_wrong.cc',
      'model/vPIFO_BMW.cc',
      'model/vPIFO_wrong_BMW.cc',
      'model/HSch_wrong.cc',
      'model/TraceCatcher.cc',
      'model/oPIFOTree.cc',
      'model/rankFIFO.cc',
      'model/TricoTree.cc',
      'model/TricoTree_rank.cc',
      'model/IdealScheduler.cc',
      'model/OnePIFO.cc',
      'model/OnePIFO_all.cc',
      'model/IdealPIFOScheduler.cc',
      'model/RRInterleavingPIFOScheduler.cc',
      'model/DynamicIntervalRRPIFOScheduler.cc',
      'model/SPPIFOScheduler.cc',
      'model/AIFOScheduler.cc',
      'model/PacksScheduler.cc',
      'model/DynamicIntervalRRPIFOScheduler_hand_dequeue.cc',
      # 'model/CreditOnly.cc',
      'model/perPIFOonly.cc',
      'model/myFIFO.cc',
      'helper/traffic-control-helper.cc',
      'helper/queue-disc-container.cc'
        ]

    module_test = bld.create_ns3_module_test_library('traffic-control')
    module_test.source = [
      'test/red-queue-disc-test-suite.cc',
      'test/codel-queue-disc-test-suite.cc',
        ]

    headers = bld(features='ns3header')
    headers.module = 'traffic-control'
    headers.source = [
      'model/traffic-control-layer.h',
      'model/packet-filter.h',
      'model/queue-disc.h',
      'model/pfifo-fast-queue-disc.h',
      'model/red-queue-disc.h',
      'model/codel-queue-disc.h',
      'model/fq-codel-queue-disc.h',
      'model/pie-queue-disc.h',
      'model/FlowScheduler.h',
      'model/MyPipeline.h',
      'model/MyScheduling.h',
      'model/PIFO.h',
      'model/SimplePIFO.h',
      'model/vPIFO.h',
      'model/vPIFO_wrong.h',
      'model/vPIFO_BMW.h',
      'model/vPIFO_wrong_BMW.h',
      'model/HSch_wrong.h',
      'model/TraceCatcher.h',
      'model/oPIFOTree.h',
      'model/rankFIFO.h',
      'model/TricoTree.h',
      'model/TricoTree_rank.h',
      'model/IdealScheduler.h',
      'model/OnePIFO.h',
      'model/OnePIFO_all.h',
      'model/IdealPIFOScheduler.h',
      'model/RRInterleavingPIFOScheduler.h',
      'model/DynamicIntervalRRPIFOScheduler.h',
      'model/SPPIFOScheduler.h',
      'model/AIFOScheduler.h',
      'model/PacksScheduler.h',
      'model/DynamicIntervalRRPIFOScheduler_hand_dequeue.h',
      # 'model/CreditOnly.h',
      'model/perPIFOonly.h',
      'model/myFIFO.h', 
      'helper/traffic-control-helper.h',
      'helper/queue-disc-container.h'
        ]

    if bld.env.ENABLE_EXAMPLES:
        bld.recurse('examples')

    bld.ns3_python_bindings()

